server:
  port: 8580
# 默认的数据库名
database:
  name: deer

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/deer?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 858414

  redis:
    database: 1
    password:
    host: 127.0.0.1
    port: 6379

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  mapper-locations: classpath:mapper/mysql/deer/*.xml

#shiro:
#  loginUrl:deerLogin/login.vue
